from __future__ import annotations

from typing import Any, Protocol

import pandas as pd

from trading_bot.core.models import ExecutionRequest, StrategyCandidate


class StrategyContract(Protocol):
    """Normalized strategy interface used by all runtime modes."""

    strategy_name: str
    setup_families: set[str]

    def prepare_trend_dataframe(self, df: pd.DataFrame) -> pd.DataFrame: ...
    def prepare_setup_dataframe(self, df: pd.DataFrame) -> pd.DataFrame: ...
    def prepare_trigger_dataframe(self, df: pd.DataFrame) -> pd.DataFrame: ...
    def analyze_market_context(self, now_utc: Any, trend_df: pd.DataFrame, setup_df: pd.DataFrame, trigger_df: pd.DataFrame, spread_points: float) -> dict[str, Any]: ...
    def generate_setup_candidates(self, market_context: dict[str, Any], trend_df: pd.DataFrame, setup_df: pd.DataFrame, trigger_df: pd.DataFrame, symbol_spec: dict[str, Any]) -> list[StrategyCandidate]: ...
    def evaluate_entry(self, candidate: dict[str, Any], trigger_df: pd.DataFrame, symbol_spec: dict[str, Any], now_utc: Any, live_profile: bool) -> dict[str, Any]: ...


class BrokerAdapter(Protocol):
    """Execution contract shared by live/demo/dry-run/backtest brokers."""

    def submit_order(self, request: ExecutionRequest) -> dict[str, Any]: ...
    def cancel_order(self, order_id: str, reason: str) -> dict[str, Any]: ...
    def modify_stop(self, position_id: str, new_stop: float, reason: str) -> dict[str, Any]: ...
    def modify_position(self, position_id: str, *, sl: float | None = None, tp: float | None = None, reason: str = "") -> dict[str, Any]: ...
    def partial_close(self, position_id: str, volume: float, reason: str) -> dict[str, Any]: ...
    def close_position(self, position_id: str, reason: str) -> dict[str, Any]: ...
    def get_open_positions(self) -> list[Any]: ...
    def get_pending_orders(self) -> list[Any]: ...
    def get_account_state(self) -> dict[str, Any]: ...
    def poll_events(self) -> list[dict[str, Any]]: ...
